### PR TITLE
Add docker to the project #6

### PR DESCRIPTION
**Pull request by sebinbenjamin**
Adding docker to the project. Fixes #7

### CODE REVIEW

**Comment by vishnudas-raveendran** [comment]
Could you please delete this file : www/presentation/academics.php

It was recently deleted in the latest merge before this pull request.

**Comment by sebinbenjamin** [comment]
Done. Something got messed up in between. Guess I should have done an interactive rebase instead of a merge from master.

**Comment by vishnudas-raveendran** [comment]
Thanks.
I think we should modify the README to explain that those who need docker setup only needs to copy that folder else just copy www into the web root directory of Apache HTTP server.

So the installation section will have two options:
1) Install via docker
2) Install with Apache HTTP Server

Does that make sense?

**Comment by vishnudas-raveendran** [comment]
> Thanks.
> I think we should modify the README to explain that those who need docker setup only needs to copy that folder else just copy www into the web root directory of Apache HTTP server.
> 
> So the installation section will have two options:
> 
>     1. Install via docker
> 
>     2. Install with Apache HTTP Server
> 
> 
> Does that make sense?

Also a description of how to setup using Docker would be great !
Would it be too trivial?

**Comment by sebinbenjamin** [comment]
Yes, 

> Thanks.
> I think we should modify the README to explain that those who need docker setup only needs to copy that folder else just copy www into the web root directory of Apache HTTP server.
> 
> So the installation section will have two options:
> 
> 1. Install via docker
> 2. Install with Apache HTTP Server
> 
> Does that make sense?

Yes. Docker would just be an additional install option.

**Comment by sebinbenjamin** [comment]
> > Thanks.
> > I think we should modify the README to explain that those who need docker setup only needs to copy that folder else just copy www into the web root directory of Apache HTTP server.
> > So the installation section will have two options:
> > ```
> > 1. Install via docker
> > 
> > 2. Install with Apache HTTP Server
> > ```
> > 
> > 
> > Does that make sense?
> 
> Also a description of how to setup using Docker would be great !
> Would it be too trivial?

Will surely add it before closing the PR.

**Review by vishnudas-raveendran — APPROVED** [review]
All good.

**Pull request merged**
